### ISSUE TITLE
Tooltips showing the title of the page

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/fcl-client#182]
When a user points with the mouse over an item like a button a tooltip is shown with the title of the page. As a user i would like to see the title or information regarding the concrete item.

Steps to reproduce the behavior (e.g. on the login page):
1. Go to 'Login'
2. Hover over 'Passwort vergessen?'
3. A tooltip appears with the text 'login'

I would expect a text like 'Gehe zu Passwort vergessen Seite' or 'Passwort vergessen'.
Another solution is to disable all tooltips.

![image.png](https://images.zenhubusercontent.com/5c35c98c4b5806bc2b01ed72/001f58cb-3ddd-4498-9510-729a677081b5)

**Comment by ruegenbfr** [comment]
The reason for that unexpected (because there is no tooltip explicitly set) tooltip is the use of the "title" attribute with the 'fcl-single-center-card-layout'-component. This attribute is passed due to inheritance to all childrens in which the attribute is not set.
In short:
The non empty 'title' attribute is responsible for the tooltip ([see](https://wiki.selfhtml.org/wiki/CSS/Tutorials/Tooltips_mit_CSS)).

Solution:
don't use title attribute
