### ISSUE TITLE
Merged stations: station label missing

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#214]
When I merge stations in the webapp and assign a label to the merged station, this label is missing after saving and reloading the JSON in the webapp

Update json: Add group name to json
Update: Import/Export, Json-Schema

Please notice related ticket: #194

**Comment by ruegenbfr** [comment]
In agreement with **bfrgottscma** the `id` and the `name` of a merged stations are identical now. The `id` and the  `name` of a merged station are written to json. During import the name is set to `id`, if the `name` is not available in the json (e.g. because its coming from the desktop app). The desktop app accepts the `name` field now, but ignores it.
