### ISSUE TITLE
Add more map types

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#288]
As a user I would like to decide which map to use. Please add e.g. shapefiles and a black&white version as in the desktop app.

Selection box box should be in header (see mockup)

**Comment by ruegenbfr** [comment]
Remark:
- Only *.geojson files are accepted as shape files.
- The projection type should be Web Mercator projection (EPSG:3857). *.geojson files with other projection types are accepted, but will look strange or misplaced.

**Comment by bfrgottscma** [comment]
Waiting for MJ to accept map server --> still pending

**Comment by afalenski** [comment]
The map Black & White works. The functionality "Load Shape File" only works with provided test files. It also works with shapefiles converted via https://mapshaper.org/ to geojson. It does not work with files from https://geojson.io (with correct coordinates without projection information), meaning that there is only a white background without any shapes. The latter is especially useful when users would like to show an incident hotspot on a map.

Any geojson should be accepted and displayed which passes the test on https://geojsonlint.com/

The ticket is now defined as done, but there will be a follow-up ticket because in the current solution only special shapefiles are accepted.

**Comment by bfrgottscma** [comment]
MJ added the new map server for dev.  For prod it still needs to be done --> MG writes email

**Comment by bfrgottscma** [comment]
Also works on Prod. Done
