### ISSUE TITLE
Footer not at bottom anymore + space above menu

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#294]
See picture below. Occurs in graph and in GIS view. Might only be true for very big monitors (e.g. 32'') or high resolution (4K)? This behaviour also occurs in full screen mode (if you press F11).
When you zoom out (Strg + -), the footer does not stay at the bottom, either. Instead, a grey area shows up below. The same grey area appears below the blue menu bar 

![Bild3.jpg](https://images.zenhubusercontent.com/5b60162df2dac06801e9e444/92c62fe4-2359-413e-9c11-46cc97c38d5f)

**Comment by bfrgottscma** [comment]
For now we put this ticket aside since it is not possible to test (availability of suitable screens). In addition, it is a problem that only applys for very large screen sizes/resolutions and this might not be relevant for the standard user.

**Comment by j-hha** [comment]
Explanation:
- we used 1fr 18fr 1fr (of 100vh) as row heights for the page
- so the header and footer rows will grow as the viewport height grows taking up 1fr of the available space
- header and footer contain components using mat-toolbar styles, setting the height of these components in pixels rather than a responsive value
- using auto 1fr auto ensures, that the header and footer rows never grow larger than their content --> no more excess whitespace

**Comment by bfrgottscma** [comment]
Nice, no space between header and menu or below footer anymore. Done.

Tested in Windows (Firefox 115.15.0esr (64-Bit) and Chrome Version 128.0.6613.138 (Offizieller Build) (64-Bit)) on a 32" monitor
