### ISSUE TITLE
Display invisible stations as ghost

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#303]
As a user I would like to temporarily see invisible stations (and according deliveries) as a ghost (semi-transparent or if too complicated > use color as it is) in the graph when hovering over an invisible station in the data table

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**Comment by birgitlewicki** [comment]
The color of the ghost station and its ghost deliveries is grey.

**Comment by bfrgottscma** [comment]
Using grey for ghosts is a good solution.

It would be great if the whole data line would react to hovering. So far ghosts are only shown if you hover over the text but not if the mouse is next to the text.

Would it be possible to show the label of the station as well?

**Comment by birgitlewicki** [comment]
The labels of stations and deliveries are shown now.

The hovering behaviour is partially improved. Could be best tested in the Country column. Bigger part of the table cell now reacts on hovering. But still the space between the table columns does not react on hovering due to technical issues.

To show ghost stations in the gis view will be described in another ticket.
