### ISSUE TITLE
Define acceptable date formats

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#412]
Please define acceptable date formats. The meaning of a date text is subjective. But especially for cross contamination tracing a correct understanding of the delivery dates is crucial.

Currently accepted: 
Format: YYYY-MM-DD
Example: 2019-08-23

**Comment by ruegenbfr** [comment]
PO wants DD.MM.YYYY too.

**Comment by ruegenbfr** [comment]
Test file[https://app.zenhub.com/files/61294409/93cc993f-bb64-4698-b678-69441b00dbb8/download](https://app.zenhub.com/files/61294409/93cc993f-bb64-4698-b678-69441b00dbb8/download):

**Comment by afalenski** [comment]
Test file was uploaded, forward trace was activated on S1 and cross contamination on S2. As the delivery from S1 to S2 is the latest of all deliveries, none of the deliveries from S2 to S2, S4 or S5 should be orange. FCL understands now the international date format YYYY-MM-DD (delivery S2 to S3) and the German date format DD.MM.YYYY (delivery S2 to S4). Both arrows are black meaning that there is no cross contamination due to the time differences in deliveries. Dates with a slash (MM/DD/YYYY) are not understood by FCL meaning that they are seen as no date and thus the delivery S2 to S5 is orange, cross contamination is assumed.

International dates and German dates are understood and evaluated in cross contamination algorithms in FCL. Done.
