### ISSUE TITLE
GIS: Geojson is not displayed

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#425]
As a user who has uploaded *.geojson files I would like to see this shapefile. I uploaded a file containing all German municipalities (see http://opendatalab.de/projects/geojson-utilities/) as well as my own geojson drawn at https://geojson.io (see attachment). Neither of these geojson files were displayed.

[Polygon-DE-0-rough.txt](https://app.zenhub.com/files/61294409/590e2a9f-0f8d-4c24-8404-41cc2a65c41b/download) (rename .txt to .geojson; geojson is not allowed in ZenHub)

Include a warning 
-> if no projection type is given, the warning should be "Projection type of geojson file not specified. Mercator projection is assumed. Map might be distorted if data do not fit Mercator projection."
 -> if wrong projection type, the warning should be "Incorrect projection type. Incorrect geojson files are not supported."

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**General Guidelines**
- Describe only one atomic unit per ticket
- Stay in the ticket scope! Be patient and write a new ticket in case of further feature requests.
- Talk with product owner if something might change for her/him.
- Improve ticket during grooming / split ticket / talk
- Do not groom / estimate without clear concept
- Tickets should be in the QA lane 24hrs before the sprint ends
- Every morning have a look whether code needs to be reviewed and directly do the review OR give feedback when you intend to do so

**Comment by ruegenbfr** [comment]
A solution has to deal with 2 aspects:

1.  The geojson is using some projection. Can the projection type be used?
2.  Provided the geojson contains an appropriate projection. Can the shapes be seen by user?

To 1.: We are using the openlayer library to visualize maps and shape files. This lib has an build in support for the the projection types 'EPSG:4326' and 'EPSG:3857' and some aliases of them. The lib provides a method to detect whether the projection is built in supported.
Ergo, **question 1 is easy to answer**, if we want to use the built in support only.

To 2.:
Event with an appropriate projection type, the user might see no shapes, either because (**Case A**) the dimension of the shapes is zero (only point of interests), or (**Case B**) the shapes are to small in comparison to the zoom scale or station distances, or (**Case C**) the shapes are out of focus (e.g. only german stations but a shape file from spain).
Case A ist easy to detect, but Case B and C depend on some defintions, in particular 'When exactly are the shapes out of focus?' and 'When are the shapes to small?'

**Comment by afalenski** [comment]
1) We should definitely use both EPSG which are WGS 84 Web Mercator / WGS 84/Pseudo-Mercator. This "...is a variant of the Mercator map projection and is the de facto standard for Web mapping applications." (https://en.wikipedia.org/wiki/Web_Mercator_projection).
2) The user needs to use one of these two projections. An imported shape must be visible, even if it is just a point of interest. Using the zoom all button in FCL Web the shapes should also be focused. This means if there are 4 stations in Germany and one shape in the USA, the zoom all button should focus the map so that stations AND shape are visible.

**Comment by ruegenbfr** [comment]
Warnings are different to the issue description:
-  If the user tries to load a geojson without a specified projection type, no warning is presented to the user, because this is in agreement with the current geojson format [specification](https://datatracker.ietf.org/doc/html/rfc7946). Which says that the projection type should not be specified and EPSG:4326 is to be used. --> Shape will be shown
- If the user tries to load a geojson with a specified projection type, and the used library supports this projection, no warning is presented to the user --> Shape will be shown
- If the user tries to load a geojson with a specified projection type, which is not supported by the used lib, the warning `Data cannot be loaded. Unsupported projection type. Please use geojson with pojection type 'EPSG:4326' or 'EPSG:3857' instead.` is shown to the user.

Please test with:
[Polygon_DE_EPSG3043.geojson](https://app.zenhub.com/files/61294409/e0b33d51-fa27-4dac-92ac-6d976930b1a1/download)
[Polygon_DE_EPSG4326.geojson](https://app.zenhub.com/files/61294409/b2addfc7-74ec-49fb-b962-2473c9e7ebd8/download)
[Polygon_DE_EPSG3857.geojson](https://app.zenhub.com/files/61294409/9aad3a27-a3e3-429e-8e8b-bfd26705852f/download)
[Polygon_DE_wo_projection_type_spec.geojson](https://app.zenhub.com/files/61294409/259ff145-db40-4649-870e-1c08c154ba0b/download)

**Comment by afalenski** [comment]
- Warning is visible with test file Polygon_DE_EPSG3043.geojson.
- The other geojson test files all show the border of Germany (very crude).

______
**Tested with**
Machine: SINA

OS: Windows 10

Datasets: 
- Example Dataset
Polygon_DE_EPSG3043.geojson
Polygon_DE_EPSG4326.geojson
Polygon_DE_EPSG3857.geojson
Polygon_DE_wo_projection_type_spec.geojson

Browsers:
- Google Chrome Version 94.0.4606.81 (Offizieller Build) (64-Bit)
- Firefox Quantum 78.15.0esr (64-Bit)
