### ISSUE TITLE
Show amount in ROA style

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#440]
As a user I would like to see the amount in the ROA style.

**To Reproduce**
- Load example data
- Click on ROA style. A small window opens showing a red triangle with an exclamation mark next to 'Amount: lotQuantity' saying "Some data is not available". 
- Click on 'Generate Report'. Amount is 'unknown' for every delivery, although there are values for amount for all deliveries.

**Expected behavior**
As all deliveries contain a value in the column 'amount', this should be displayed in the ROA style. LotQuantity should be connected with the amount data.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by ruegenbfr** [comment]
The property 'Amount' from the desktop app is a delivery specific property not a lot specific property.
Several deliveries can originate from the same lot but their amount can differ. 
'lotQuantity' is the name of the property, which is supposed to contain the amount of the lot. This value is provided by the distiller workflow.

However, the bug here is:
The list of selectable properties in the 'Lot Box Label' configuration is missing some values, e.g. 'lotQuantity' if supplied.

Expected behavior:
The list should contain all delivery properties specified in the input model, but the properties known to be delivery specific (id, delivery dates, score, weight, crossContamination, forward, backward, observed, invisible, selected, source, target) or having ambiguous values within a lot, e.g. the deliveries 'D1' from lot 'L' with an 'amount' of '50 kg' and 'D2' from lot 'L' with an 'amount' of 100 kg have different values for the property 'amount'.

Observed behavior:
The property list for a distiller output model contains only 'lot' and 'name'.

**Comment by afalenski** [comment]
@ruegenbfr As you show in your example the amount is always a combination of a number and a unit. The unit is missing in the ROA style. Without unit the user cannot make sense of the numbers which are shown behind "amount:" in the ROA Style. Please correct so that there is always a number with a unit.
- Column "amount": No need for extra data because number and unit are both shown in this column.
- Column "_lieferungen.delivery_amount": Autmatically display the unit from the corresponding column "_lieferungen.delivery_unit" behind the number in the ROA Style.

Example:
- Load Baby Tea dataset (Scenario_1_Outbreak-Baby-Tea.json)
- Click on ROA Style
- In the opening ROA Report Configuration window select "_lieferungen.delivery_amount"
- Click on "Generate Report"
- In the ROA report the first box in the top left for station "Primary producer: Organic Herbs Egypt Inc. (OHEI)" shows the product details:
_Dried organic camomille flowers, Lot no. DC 17
Lot: 1799261720
Amount: 6000_
It remains unclear, whether the unit is packages, tons or something else.

Expected result:
_Dried organic camomille flowers, Lot no. DC 17
Lot: 1799261720
Amount: 6000 **kg**_
