### ISSUE TITLE
FCL-Web-App: Does not support äöuß (Umlaute, Eszett)

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#46]
Please support "Umlaute" etc and sharp s (äöuß). You can test it with the norovirus scenario data as JSON (see attachment).
[Norovirus_scenario_data.zip](https://github.com/SiLeBAT/fcl-web-app/files/1707350/Norovirus_scenario_data.zip)

JSON format should be utf8 (import and export)

Recherche: 2 days

Maybe think about FAQ that says "if funny letters --> ensure yor format is UTF8"

**Comment by ruegenbfr** [comment]
Facts:
- According to the latest JSON format standard (RFC 8259):
JSON text exchanged between systems that are not part of a closed ecosystem MUST be encoded using UTF-8.
- The release version 1.1.38 exports UTF-8 format. (TracingView and JSON Writer Node).
 
To verify: Is there a valid auto detection of utf-8?

**Comment by bfrgottscma** [comment]
I choose the second solution (implement utf-8 encoding check and stop loading of files with no valid utf-8 encoding) since it makes no sense to be able to load data into FCL Web which you can't save afterwards.

Please also include a warning for the user when loading a non-UTF-8 file fails. "Data cannot be uploaded. Please ensure to upload only data encoded in UTF-8 format."

**Comment by bfrgottscma** [comment]
works in Chrome but not in Firefox

**Comment by ruegenbfr** [comment]
Works in Chrome, Firefox, Safari and Edge now.
