### ISSUE TITLE
UI not responding after entering pw on registration page

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/fcl-client#552]
This is a rare bug. When entering a password into the registration form the UI can become stale up to several seconds.
This also can effect the e2e tests not being able to perform requested operations.

Reproduce:
- navigate to registration page
- enter "1234" into the password field
- quickly click into another form field for editing
=> sometimes the ui doesn't respond for up to several seconds
Testet on: Windows 10, Chrome

Dev-Note:
I isolated the bug to the password-strength-meter component. For unknown reason this library blocks the ui sometimes if the input changes. Updating the lib to 3.0.1 causes same issues.
Best (fast and easy) solution: Abandon this buggy library and implement an own strength meter.

**Comment by afalenski** [comment]
Tested 10x in Chrome and 6x in Firefox. The bug was not seen.

@ruegenbfr Was the code changed to get rid of the bug or is the bug that rare that it cannot always be reproduced?
______
**Tested with**
OS: Windows 10

Browsers:
- Google Chrome Version 91.0.4472.77 (Offizieller Build) (64-Bit)
- Firefox Quantum 68.9.0esr (64-Bit)

**Comment by GerberI** [comment]
@afalenski 
I checked it again, now the ui freeze is under a second (perhaps due to a chrome update or something), so only issue is that you have to click two times in rare conditions. So the problem is only relevant for the e2e tests and i have fixed them already.

Also the register form will be replaced in the feature by the keycloak register form, so i closed the issue.
