### ISSUE TITLE
Loading of example data set: Trigger save message box

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#638]
When loading a new example data file, the current data will be discarded to prevent performance issues.
A message box should be triggered which informs the user that data are discarded and which asks the user if he/she would like to save the data.
"Do you want to save the changes you made to "[FileName]"? Your changes will be lost, if you do not save them"  --> 3 Buttons: 
- **Save** (close message box, trigger save dialogue, (if possible: when saved trigger loading of selected dataset)) --> Button "Save" should be active by default.
- **Don't save** (close message box and load new dataset without saving)
- **Cancel** (close message box, stay in old dataset) 

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**General Guidelines**
- Describe only one atomic unit per ticket
- Stay in the ticket scope! Be patient and write a new ticket in case of further feature requests.
- Talk with product owner if something might change for her/him.
- Improve ticket during grooming / split ticket / talk
- Do not groom / estimate without clear concept
- Tickets should be in the QA lane 24hrs before the sprint ends
- Every morning have a look whether code needs to be reviewed and directly do the review OR give feedback when you intend to do so

**Comment by bfrgottscma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-client/638?planning-poker) with ZenHub @afalenski @birgitlewicki @GerberI @ruegenbfr

**Comment by bfrgottscma** [comment]
Works as described for loading example data. Dialogue is not triggered by initial loading of data. As soon as another example dataset is loaded, the dialogue is always triggered no matter if the currently loaded data is example dataset or your own dataset.

When "Save" is chosen from the dialogue, the Save dialogue is triggered but the new dataset is loaded immediately which could confuse the user. This is an in-build feature of the browser when user chose the setting "ask for save location before download". For automated download it works as intended. 
Decide if an additional note in the message box should be added or if we should look for an additional library to solve this issue.

Tested on Windows 10 system in
- Firefox (101.0.1 (64-Bit))
- Chrome (Version 103.0.5060.66 (Offizieller Build) (64-Bit))

**Comment by afalenski** [comment]
- When editing an example file (Example data, drag station in the graph) and choosing example file Babytea Scenario 1, the new message box appears.
- Save, Don't save and Cancel work fine.
- [ ] The message in the message box does not fit to the ticket text: The file name is not stated, but only the general term "data" is shown.
- [ ] When the message box appears and you click "Save", the new dataset is immediately shown although the user is still saving the old dataset. The behaviour of the app feels even stranger if you are in the map view and select a new example file, because during saving you suddenly see the graph view with the new dataset. If the loading of new data cannot be postponed until the save action is completed, the new dataset should be hidden (white graph /map area).
- [ ] Having loaded an example dataset (e.g. Example Data) and - without changing anything - clicking on a different example dataset (e.g. Babytea Scenario 1), the message box appears. This is unnecessary and annoying. The same is true for uploading a JSON file and then loading an example dataset.
- [ ] [Not in this ticket scope, but necessary:] When changing Example Data (by dragging a station in the graph) and uploading a JSON file the message box does NOT appear. This is inconsistent and unexpected. It should be added within a new ticket.
- [ ] [Not in this ticket scope, but necessary:] When uploading a JSON file and after changing something, clicking again on "Upload data" does NOT trigger the message box.

______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Datasets: 
- Example Data
- Babytea Scenario 1

Browsers:
- Firefox 91.10.0esr (64-Bit)

**Comment by birgitlewicki** [comment]
Change button text "Save" to "Save Current and Load New".
Default file name = current file name

**Comment by birgitlewicki** [comment]
- change button text: done
- change default file name: done
- when saving a data set with 'download data' the current file name of this data set is now shown in the save dialog, instead of the former default file name 'data.json'

**Comment by afalenski** [comment]
- Filename is stated in message box
- [ ] When the message box appears and you click "Save", the new dataset is immediately shown although the user is still saving the old dataset. The new dataset should be hidden (white graph /map area) as discussed in the ticket review.
- [ ] When example dataset A has been loaded and dataset B is selected,  the dialogue is triggered. If the user selects button "Save current and load new", dataset B is shown in the background without being hidden (see above). However, if the user aborts saving, dataset A is not shown again and all progress is lost. This is unacceptable. Please change.

**Comment by birgitlewicki** [comment]
A two-step approach and further improvements will be implemented in Tickets #680, #668, #669

**Comment by afalenski** [comment]
Regarding the change in the approach for the save dialogue it is unclear to me what needs to be tested in this ticket. What has been done in this ticket that I can see as user (and test)? I will test the save dialogue when fcl-c680 and fcl-c669 are done as these seem to cover the current idea of the save dialogue.

**Comment by bfrgottscma** [comment]
Ticket is done since there are fundamental changes of the concept of the save dialogue that are dealt with in #680 and #669. they will be tested separately
