### ISSUE TITLE
Implement FAQ page

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#713]
As a user I would like to get information on e.g. technical requirements of FCL Web and its handling. Please add an FAQ page.

For Mockup see MibiPortal.
- the FAQ button should be placed in footer of FCL Web (between "Data Protection Declaration" and "Report a problem")
- clicking on this button links to FAQ page
- with regard to design of the FAQ page, use default settings of Angular material as often as possible (in contrast to MibiPortal design)
- the FAQ page (at MibiPortal) looks like this 
![FAQ.png](https://images.zenhubusercontent.com/5b60162df2dac06801e9e444/2b67a6a8-0491-4345-af0f-d6ba5fa591ad)

- on the top are the section headings. Clicking on a topic scrolls to the specific section.
- the questions are nested within the sections.
- you can expand/collapse the answer to the questions by clicking on the arrow on the right side.

- Content is provided by the P/O via a JSON file (add title column in the JSON file/Excel)

CAVE: 
- scrolling could cause problems (e.g. when using the "back" button or switching to a different page within FCL Web)
- please take care that loaded models in Tracing view remain available (same as for ROA style) when going to FAQ and back to Tracing view

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**Comment by bfrgottscma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-client/713?planning-poker) with Zenhub @birgitlewicki @GerberI @ruegenbfr

**Comment by ruegenbfr** [comment]
FAQ page created. The state of the tracing view is not affected by navigations to faq view.

Please check:
- page title
- section header colors

**Please note**: The state of ROA view is lost, if the user switches from roa view to faq view (The user has to approve the switch). If the user goes back to roa view (browser history back) all roa view changes are gone.

**Comment by afalenski** [comment]
- Please use the blue colour from MiBi-Portal Dev: https://epilab-dev.bfr.berlin/faq
- Please change the font colour to white when the background is blue.
- Change card width: The text is easier to read when the text line is not as long; change to width as in MiBi-Portal (see above).
- ROA: There is already a warning when the ROA is open and you click the FAQ-Link. This is enough.

**Comment by afalenski** [comment]
- Links to section headings work
- expanding and collapsing cards works
- Links to login page work
- Text is easy to read due to reduced card width
- Having loaded a dataset and opening the FAQ page, the dataset is still there when returning from FAQ page (either via Tracing View button or via browser button 'back')
- Nice (former) BfR blue
- Scrolling down on FAQ page, going to Tracing View and then back to FAQ page (either via FAQ button or via browser button 'back') the FAQ page is shown at the top. But this is OK.
Done
______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Datasets: 
- Example Data

Browsers:
- Firefox 91.13.0esr (64-Bit)
- Google Chrome Version 104.0.5112.102 (Offizieller Build) (64-Bit)
