### ISSUE TITLE
Update Angular from version 13 to 14 

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#724]
Update Angular dependencies  to version 14, because version 14 is not anymore maintained.

**Comment by ruegenbfr** [comment]
Please check ui for style changes.

**Comment by afalenski** [comment]
All tests were done both in Firefox and Chrome.

- BUG When re-doing the test in fcl-c560 "Make the complex filter faster", ghost values were visible when doing the following: Click into ohne ID value box and scroll with the mouse wheel: Values appear above or below the scroll box containing all the IDs (see screenshot "Bug_HighlightingComplexFilter_ScrollWithMouseWheel.png").
- PERFORMANCE Loading ROA of BabyTea3 took about 30 seconds. Once loaded, scrolling was fast, but zooming also took several seconds (~7-8s). With the "Example Data" dataset loading ROA took 1 second and zooming worked instantly.
- The red "draft" label covers the "l" of the "ROA Style" button (just noticed, it is the same in the prod version).

Highlighting
- OK Switching a label or colour/shape on and off worked.
- OK Deleting  a label or colour/shape worked.
- OK Deactivating and activating the display of a label rule in the legend worked.
- BUG When editing the StationLabel by Adding "Use conditions" with Type of Business = Bakery and after pressing the Apply button, only the bakeries have station labels (as expected). However, when clicking the Cancel button, the label editor closes and still only the 3 bakeries have a label. I would expect that the added rule will be discarded (because I did not press "OK"). The same behaviour of the Apply and Cancel buttons is in the Colour and Shapes edit menu and in the same menus in the delivery delivery tab.

- BUG When opening the Page Setup in the ROA view, the number in the Grid Size display is truncated (only Firefox, see fcl-c652)
- OK When uploading a wrong JSON file, the error message stays as long as the user does not left click anywhere.
- OK FAQ page looks nice, buttons work.
- OK Mouse cursor blinks in email field when opening login page, login works.
- OK Shapefile is loaded, borders can be coloured.
- OK Center supply chain in visible area works.
- OK Default node and text size is 14.
- OK Edge width can be changed manually.
- OK Testing Ticket fcl-c676 again showed no bug.
- OK Testing Ticket fcl-c697 again showed no bug.
- OK Testing Ticket fcl-c691 again showed no bug.
- OK Testing Ticket fcl-c699 again showed no bug.
- OK Testing Ticket fcl-c704 again showed no bug.
- OK Testing Ticket fcl-c709 again showed no bug.
- DEPENDS Testing fcl-c727: Avatar head and text are not overlapping anymore. However, the gap between avatar head and user name / email is narrower than in the profile and logout row. The gap should have the same width in every row.
- OK Testing fcl-c726 Done
- OK Testing fcl-c728 and fcl-c729 Done
- OK Testing fcl-c720 Done

______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Datasets: 
- Example Data
- Babytea Scenario 1

Browsers:
- Firefox 102.12.0esr (64-Bit)
- Google Chrome Version 114.0.5735.110 (Offizieller Build) (64-Bit)

**Comment by ruegenbfr** [comment]
- GHOST-Value-Bug in filter conditions: The bug was not introduced by angular update. The bug was introduced by the virtual scroll (condition) list feature
- ROA performance issue: performance did not change from current prod version to current release candidate. (Firefox 102.14, Chrome 115.0...)
- Apply Edit Rule Bug: This is no bug, its standard behaviour. Apply has the same effect as OK, but without closing the edit mode. So if you use 'Cancel' after 'Apply' only the changes, which have been made after 'Apply' are discarded.
- ROA GridSize truncation bug: Was not introduced by angular update, should have been addressed but was not detected in ticket 
- Avatar header issue: The smaller gap was choosen because of the different font size of the name/email. The different font size was used before. An alignment of the entries with different font sizes looks unfitting too. **@MG** please decide

**Comment by ruegenbfr** [comment]
GHOST-Value-Bug is addressed in ticket #736
