### ISSUE TITLE
Release preparations

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#749]
Please prepare the next release of FCL Web (Including anonymisation feature).

ToDos
- Minify JSON (see ticket)
- rename Delivery names in BabyTea (all 3 versions) and adapt delivery labels (show name and lot no)

**Comment by ruegenbfr** [comment]
fcl-server has a moderate [vulnerability](https://github.com/advisories/GHSA-wf5p-g6vw-rhxx). 

This vulnerability is caused by a transitive dependency **pm2** -> **@pm2/js-api** -> **axion** 
The vulnerability was fixed in **axion** version 1.6.0, but the latest version (0.7.0) of **@pm2/js-api** is still requiring version **^0.21.0**.

#### Solutions available:
- wait for fix
- force fcl-server to use **axion** version **^1.6.1** 
- use release version with this vulnerability

#### Current status: 
Dev preferred solution: waiting for fix
Current step: Waiting for new version of **@pm2/js-api**
Next step: waiting for new version of **pm2**, because the latest **pm2** is requiring **@pm2/js-api** in version **~0.6.7**
