### ISSUE TITLE
Improve FCL banner in ROA PDFs

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-client#778]
As a user I do not want to print a supply chain in which elements of the image (here: FCL banner) is cut off.

Note: This issue did not occur before the last ROA changes (several tickets).

The screenshots show that there is plenty of space below the banner, so the banner could be displayed completely. Perhaps the margins need to be edited...

PDF printed in Firefox:
<img width="258" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1NUQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c52caa4e445691f54e3f89b98621562b6919bb5d/grafik.png" alt="grafik.png" />

Zoom in:
<img width="1199" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1dUQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--85ae3f7d08c3609b8bd3436f5647fa614a7f87c3/grafik.png" alt="grafik.png" />

PDF printed in Chrome, page 1:
<img width="452" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2VUQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3a852c0aa3debda87ccfe90711fc43c376c18af5/grafik.png" alt="grafik.png" />

Zoom:
<img width="1128" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2lUQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5c8aed45ecc6734a5b3252279eea58758012a80d/grafik.png" alt="grafik.png" />

Page 3:
<img width="596" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK21UQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e891a795638a7b2f68fc55715d1c6be80cffed71/grafik.png" alt="grafik.png" />

**Comment by ruegenbfr** [comment]
##### Why the FCL banner is cut off?
Because of its position. The graph editor shows the page breaks as dashed lines. They are dependent on the page size and the page orientation. The lines show that the page break is in the middle of the FCL banner. 

##### Why is there space in the pdf dodument?
The graph editor reduces the page scale (default 100 %) internally. What ever the user chooses the graph editor uses only 75% of that choice. (The reason for that hard coded scale reduction is given as 'Workaround to match available paper size in actual print output'). 
If this internal reduction is removed than the cut in the pdf document is usually even bigger. Because usually the browser printer settings respect a margin. The user can choose to print without margin in the printer dialog and than there is no space left in the pdf document.
So this hard coded reduction was probably introduced because of the printer margins. The printer margins can be customized in a browser and their default values seem to be different for different browsers.

##### Proposed solution to prevent legend/banner cut:
- reduce vertical inter layer box space:
  - decent vertical country box distance reduction
  - halve vertical station box distance, if they are in adjacent layers and all station boxes in these adjacent layers are within one countrybox

  --> the examples will not show the banner cut off anymore, because the height of the graph is reduced
- If the area containing the legend and the banner is cut by a horizontal page break, move it initially (when the roa report is created and the report is shown) south such that this area is not cut anymore. 
  Please note: This respects only the initial settings of page size and orientation.

@afalenski decided to reduce at first only the vertical box distance. The move of the legend shall be addressed in a separate ticket.

**Comment by afalenski** [comment]
Banner is not cut off in Firefox or Chrome for Example Dataset and BabyTea Scenario 1.
Done.

______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Datasets: 
- Example Data
- Babytea Scenario 1
- Babytea Scenario 2

Browsers:
- Firefox 115.11.0esr (64-Bit)
- Google Chrome Version 125.0.6422.142 (Offizieller Build) (64-Bit)
