### ISSUE TITLE
Make station property dialogue movable

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#803]
As a user I would like to be able to move the station property dialogue since it sometimes hides relevant stations and deliveries in the graph. 
- [x] The dialogue (modal) should be movable with drag-and-drop when dragging on the upper edge of the dialogue as regular windows do. 
- [x] To highlight this behaviour for the user, please include a four-way arrow as a pick handle in the right upper corner of the window. 
- [x] It should not be possible to move dialogue out of browser window. (Behaviour when resizing the browser window and other corner cases will be discussed when first implementation is ready to test)
- [x] Please also rename the "OK" button in the dialogue to "Close" button.
- [x] When clicking the Close button or clicking somewhere outside of the Station Properties dialogue, the dialogue is closed.

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**Comment by afalenski** [comment]
Outcome of today's discussion:
- If a (property dialogue) window pops up and the background is greyed out, the user expects that his/her attention should be on the new window and that the background is not relevant. Thus, the window should stay centered as it is now and no action should be possible in the graph.
- If a window is movable, the user expects the graph / map to be editable, which means it should not be greyed out.
Suggestion: The property dialogue stays centered, the graph / map stays greyed out, but when the user hovers over the deliveries in the properties dialogue window, only there are the deliveries highlighted. In the greyed out graph no delivery should be highlighted anymore. It does not make sense to draw the user's attention to a greyed out graph / map in which most is hidden by the dialogue and where seeing deliveries and stations is hard because it is greyed out.
@bfrgottscma Would this change in the ticket be okay for you?

**Comment by bfrgottscma** [comment]
Dialogue pops up in center but is movable. Behaviour of canvas stays as is.
Rename OK button to Close button, add moving controls to right corner of window.

**Comment by arne-z** [comment]
Possible Icons: https://thenounproject.com/browse/icons/term/move/

**Comment by afalenski** [comment]
- The dialogue is movable with drag-and-drop when dragging on the upper right edge of the dialogue (drag symbol)
- The dialogue can be moved on the whole browser tab: In front of an open filter table, the blue menu bar and the legend. The rest of the tab is behind a grey veil.
- The "OK" button is now a "Close" button.
- When clicking the Close button or clicking somewhere outside of the Station Properties dialogue, the dialogue is closed.
- Hovering over deliveries or connection between deliveries in the properties dialogue still highlights them in the graph / on the map.
Done.
______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Datasets: 
- Example Data
- Babytea Scenario 3

Browsers:
- Firefox 115.15.0esr (64-Bit)
